language: python
python:
  - "2.7"
install:
    - pip install coveralls --use-mirrors
# command to run tests
script:
  coverage run --source=django_template_i18n_lint setup.py test
after_success:
  coveralls
